contact_links:
  - name: Общение / Communication
    url: https://t.me/FoxCloud
    about: Общение между другими пользователиями в группе Телеграмма / Communicate with other users in the Telegram group
